const ADD_POST = "ADD_POST";
const UPDATE_POST = "UPDATE_POST";
const ADD_TAG = "ADD_TAG";
const UPDATE_TAG = "UPDATE_TAG";
const ADD_SECTION = "ADD_SECTION";
const UPDATE_SECTION = "UPDATE_SECTION";
const ADD_SUBSECTION = "ADD_SUBSECTION";
const UPDATE_SUBSECTION = "UPDATE_SUBSECTION";

export {
    ADD_POST,
    ADD_SECTION,
    ADD_SUBSECTION,
    ADD_TAG,
    UPDATE_POST,
    UPDATE_SECTION,
    UPDATE_SUBSECTION,
    UPDATE_TAG
}
